name: SSL Monitor

on:
  schedule:
    - cron: "30 3 * * *"

  workflow_dispatch:

jobs:
  ssl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - name: SSL Monitor
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python ssl_monitor.py
